repositories:
  # Load Balancers
  - name: jetstack 
    url: https://charts.jetstack.io  

releases: 
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.3
    timeout: 600
    labels:
      app: cert-manager
      tier: infrastructure
    values:
      - values-cert-manager.yaml
    #--These hook ensure that the PKI is bootstrapped and all
    #--certificates are active after helm has synced the release
    hooks:
    # - events: ["postsync"]
    #   showlogs: true
    #   command: kubectl
    #   args:
    #     - apply
    #     - -f
    #     - pki-bootstrap.yaml
    - events: ["postsync"]
      showlogs: true
      command: kubectl
      args:
        - apply
        - -f
        - cert-manager-issuers.yaml    
