repositories:
  # Load Balancers
  - name: jetstack 
    url: https://charts.jetstack.io  

releases: 
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.3
    timeout: 600
    labels:
      app: cert-manager
      tier: infrastructure
    #values:
    #  - values-cert-manager.yaml
    #--These hook ensure that the PKI is bootstrapped and all
    #--certificates are active after helm has synced the release
    #hooks:
    # - events: ["postsync"]
    #   showlogs: true
    #   command: kubectl
    #   args:
    #     - apply
    #     - -f
    #     - pki-bootstrap.yaml
    # - events: ["postsync"]
    #   showlogs: true
    #   command: kubectl
    #   args:
    #     - apply
    #     - -f
    #     - cert-manager-issuers.yaml    


# - name: cert-manager
#     namespace: cert-manager
#     chart: jetstack/cert-manager
#     version: v0.14.2
#     atomic: true
#     hooks:
#       - events: ["presync"]
#         command: "/bin/sh"
#         args: ["-c","kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/{{`{{ .Release.Version }}`}}/cert-manager.crds.yaml > /dev/null 2>&1 || true"]
#     values:
#       - installCRDs: true

#   - name: letsencrypt-cert-issuer
#     namespace: cert-manager
#     chart: incubator/raw
#     installed: {{ exec "./do.sh" (list "testCerManagerCRDExists") | trim }}
#     needs:
#       - cert-manager/cert-manager
#     values:
#       - resources:
#           - apiVersion: cert-manager.io/v1alpha2
#             kind: ClusterIssuer
#             metadata:
#               name: letsencrypt-prod
#             spec:
#               acme:
#                 server: https://acme-v02.api.letsencrypt.org/directory
#                 email: {{ .Values.acme_email }}
#                 privateKeySecretRef:
#                   name: letsencrypt-prod
#                 solvers:
#                   - selector: {}
#                     http01:
#                       ingress:
#                         class: traefik        
