# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
keys:
  - &primary age1wg93d32ww6l3euq2xcrufdjly24avfzm8kt0svkpl2ardgs94spqktmhjv
creation_rules:
  - path_regex: .*secrets.yaml$
    key_groups:
    - age:
      - *primary
      
  - path_regex: profiles\/*.secrets.yaml$
    key_groups:
    - age:
      - *primary
